### ISSUE TITLE
RかVASTのバージョンの違いによって結果が変わる

### ISSUE THREAD

**Issue by ShotaNishijima** [ShotaNishijima/vast_workshop2020#11]
- RのバージョンかVASTのバージョンが違うとtest_codeの結果が変わる
- 古いとaniso.pngが左に傾き、新しいと右に傾く
- indexの値も結構変わる
- なぜ？？？

**Comment by ShotaNishijima** [comment]
`install.github("james-thorson/FishStatsUtils", INSTALL_opts="--no-staged-install")`
でFishStatsUtilsをVersion 2.1.0から2.4.0に更新したら、結果が変わりました。

FishStatsUtils 2.1.0: 
![Aniso](https://user-images.githubusercontent.com/44153027/72080548-537f5a00-3340-11ea-8db4-35895f48e215.png)

FishStatsUtils 2.4.0:
![Aniso](https://user-images.githubusercontent.com/44153027/72080604-672ac080-3340-11ea-96d3-509e28c38bfd.png)

原因はFishStatsUtilsっぽいですが、どちらが正しいのでしょうか…

**Comment by Yuki-Kanamori** [comment]
FishStatsUtilsのバージョンでデータの中身って違うのでしょうか？

**Comment by ShotaNishijima** [comment]
'Save.RData'に保存されているTmbDataをチェックしたところ、データは同じようです…

**Comment by ShotaNishijima** [comment]
VASTとFishStatsUtilsのバージョンが対応していれば（VASTインストール時に自動でインストールされるFishStatsUtilsを使っていれば）、たとえ古いバージョンでも上記の問題は生じないようです。僕の場合はFishLifeを使う際に古いバージョンのFishStatsUtilsを再インストールしたことで結果が変わったようです。下のanisoの図が正解です。
